apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: homepage
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: mt165.co.uk
    http:
      paths:
      - backend:
          serviceName: homepage
          servicePort: http
  - host: www.mt165.co.uk
    http:
      paths:
      - backend:
          serviceName: homepage
          servicePort: http
  tls:
    - hosts:
      - mt165.co.uk
      - www.mt165.co.uk
      secretName: homepage-tls
