apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: "letsencrypt-staging"
spec:
  rules:
  - host: blog.mt165.co.uk
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: http
  tls:
    - hosts:
      - blog.mt165.co.uk
      secretName: blog-tls
