apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: blog
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: blog.mt165.co.uk
    http:
      paths:
      - backend:
          serviceName: blog
          servicePort: http
