apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: blog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blog
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60
